# Generated by Django 4.1.3 on 2022-11-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20221101_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_member', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=25)),
                ('alamat', models.CharField(max_length=20)),
            ],
        ),
    ]
