# Generated by Django 4.1.3 on 2022-11-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id_member',
        ),
        migrations.AddField(
            model_name='member',
            name='idmember',
            field=models.CharField(default='NIM', max_length=30),
        ),
    ]
